#ifndef DS18B20_H
#define DS18B20_H

#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "onewire_library.h"
#include "onewire_library.pio.h"        // generated by pioasm

typedef struct {
    OW ow;
    uint64_t rom_code;
    bool initialized;
} DS18B20;

bool ds18b20_init(DS18B20 *dev, PIO pio, uint gpio);
float ds18b20_read_temp(DS18B20 *dev);

#endif